version: "3"
services:
  web:
    build: ./
    ports:
      - "4000:8080"
      - "9229:9229"
    volumes:
      - "./src/index.js:/usr/src/index.js"
    depends_on:
      - db
    links:
      - db
  db:
    image: "postgres:11"
    restart: always
    ports:
      - 5439:5432
    env_file:
      - .env
      
  migration:
      build: ./
      command: ["./wait-for-it/wait-for-it.sh", "db:5439", "--", "npm", "run", "migrate"]
      links:
        - db
      depends_on:
        - db